FROM trion/ng-cli-karma as node
WORKDIR /app

COPY kadmium-reaper-remote.WebUI/package.json /app/
RUN npm install

COPY kadmium-reaper-remote.WebUI/ /app/
ARG env=production

RUN ng test --watch false
RUN npm run build -- --prod --configuration=$env

FROM microsoft/dotnet:2.1-sdk AS aspnetcore-build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY kadmium-reaper-remote.WebAPI/*.csproj ./kadmium-reaper-remote.WebAPI/
COPY kadmium-reaper-remote.sln .
RUN dotnet restore

# Copy everything else and build
COPY kadmium-reaper-remote.WebAPI/ ./kadmium-reaper-remote.WebAPI/
RUN dotnet publish -c Release -o out
COPY --from=node /app/dist kadmium-reaper-remote.WebAPI/out/wwwroot

# Build runtime image
FROM microsoft/dotnet:2.1-aspnetcore-runtime
EXPOSE 80
WORKDIR /app
COPY --from=aspnetcore-build-env /app/kadmium-reaper-remote.WebAPI/out .
ENTRYPOINT ["dotnet", "kadmium-reaper-remote-dotnet.dll"]