version: "3.6"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: kadmium/kadmium-reaper-remote:0.1
    volumes:
      - kadmium-reaper-remote-volume:/app/kadmium-reaper-remote/data
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
volumes:
  kadmium-reaper-remote-volume:

networks:
  webnet:
