version: '3.6'
services:
    reaper-remote:
        restart: unless-stopped
        image: 'kadmium/kadmium-reaper-remote:latest'
        volumes:
            - 'kadmium-reaper-remote-volume:/app/kadmium-reaper-remote/data'
        deploy:
            mode: global
            restart_policy:
                condition: none
        ports:
            - '80:80'
        networks:
            - webnet
volumes:
    kadmium-reaper-remote-volume: null
networks:
    webnet: null
